export const COMPANY_NOT_FOUND = 'Cannot find company for given account.'
export const COMMIT_ALREADY_SET = 'Commit has already been set.'
export const COMMIT_CANNOT_MATCH = 'Next commit cannot match current commit.'
export const COMMIT_NOT_SET = 'Commit has not been set.'
export const EPOCH_NON_ZERO = 'Epoch must be greater than zero.'
export const EPOCH_NOT_READY = 'Current epoch is not ready to advance'
export const ERROR_SYSTEM_ALREADY_INITIALIZED = 'This game has already been initialized.'
export const ERROR_SYSTEM_DISABLED = 'This game is currently disabled.'
export const ERROR_SYSTEM_NOT_INITIALIZED = 'This game has not been initialized.'
export const GAME_NOT_FOUND = 'Cannot find game for given account name.'
export const GAME_SEED_NOT_SET = 'This game has not initialized an epoch seed value.'
export const ITEM_DOES_NOT_EXIST = 'Item does not exist.'
export const INVALID_AMOUNT = 'Invalid amount.'
export const REQUIRES_MORE_THAN_ONE = 'A value greater than one is required.'
export const REQUIRES_POSITIVE_VALUE = 'Value must be greater than zero.'
export const PLAYER_ALREADY_JOINED = 'Player has already joined the game.'
export const PLAYER_NOT_JOINED = 'Player has not joined the game.'
export const PLAYER_NOT_FOUND = 'Cannot find player for given account name.'
export const STARTER_ALREADY_CLAIMED =
    'Starter ship already claimed; destroy existing ships to re-claim.'
export const SHIP_ALREADY_THERE = 'Ship cannot travel to the location its already at.'
export const SHIP_ALREADY_TRAVELING = 'Ship is already traveling.'
export const SHIP_CANNOT_BUY_TRAVELING = 'Ship cannot buy goods while traveling.'
export const SHIP_CANNOT_UPDATE_TRAVELING = 'Ship cannot be updated while traveling.'
export const SHIP_INVALID_DESTINATION = 'Ship cannot travel, no system at specified destination.'
export const SHIP_INVALID_TRAVEL_DURATION =
    'This trip cannot be made as it would exceed the maximum travel duration.'
export const SHIP_NOT_ARRIVED = 'Ship has not yet arrived at its destination.'
export const SHIP_NOT_ENOUGH_ENERGY =
    'Ship does not have enough energy to travel to the destination.'
export const SHIP_NOT_ENOUGH_ENERGY_CAPACITY =
    'Ship does not have enough energy capacity to travel.'
export const SHIP_NOT_FOUND = 'Cannot find ship for given account.'
export const SHIP_NOT_OWNED = 'Ship is not owned by this account.'
export const NO_SCHEDULE = 'No scheduled tasks.'
export const SHIP_NOT_IDLE = 'Ship must be idle (no active schedule) for this action.'
export const SHIP_NO_COMPLETED_TASKS = 'No completed tasks to resolve.'
export const RESOLVE_COUNT_EXCEEDS_COMPLETED = 'Requested resolve count exceeds completed tasks.'
export const SHIP_CANNOT_CANCEL_TASK = 'Cannot cancel task that is immutable or in progress.'
export const SHIP_NO_TASKS_TO_CANCEL = 'No tasks to cancel.'
export const SHIP_INVALID_CARGO = 'Invalid cargo specified for load/unload.'
export const SHIP_CARGO_NOT_OWNED = 'Cannot load cargo that is not owned.'
export const SHIP_CARGO_NOT_LOADED = 'Cannot unload cargo that is not loaded.'
export const SHIP_CAPACITY_EXCEEDED = 'Ship cargo capacity would be exceeded.'
export const ENTITY_CAPACITY_EXCEEDED = 'Entity cargo capacity would be exceeded.'
export const WAREHOUSE_NOT_FOUND = 'Cannot find warehouse for given id.'
export const WAREHOUSE_ALREADY_AT_LOCATION = 'Warehouse already exists at this location.'
export const WAREHOUSE_CAPACITY_EXCEEDED = 'Warehouse capacity would be exceeded.'
export const CONTAINER_NOT_FOUND = 'Cannot find container for given id.'
export const CONTAINER_CAPACITY_EXCEEDED = 'Container capacity would be exceeded.'
export const DESTINATION_CAPACITY_EXCEEDED =
    'Destination entity does not have enough capacity for the gather.'
export const CANCEL_PAIRED_HAS_PENDING =
    'Cannot cancel transfer, paired entity has pending tasks.'
export const GROUP_EMPTY = 'Group travel requires at least one entity.'
export const GROUP_NO_THRUST = 'Group travel requires at least one entity with engines.'
export const GROUP_NOT_SAME_LOCATION =
    'All entities must be at the same location for group travel.'
export const GROUP_NOT_SAME_OWNER = 'All entities must have the same owner for group travel.'
export const GROUP_ENTITY_NOT_MOVABLE = 'Entity cannot participate in group travel.'
export const GROUP_NOT_FOUND = 'Entity group not found.'
export const GROUP_DUPLICATE_ENTITY = 'Duplicate entity in group.'
export const GROUP_HAUL_CAPACITY_EXCEEDED =
    'Group travel requires sufficient hauler capacity for all non-self-propelled entities.'
export const CANCEL_CONTAINS_GROUPED_TASK =
    'Cannot cancel range containing grouped task - cancel non-grouped tasks first.'
export const WARP_NO_CAPABILITY = 'Entity does not have warp capability.'
export const WARP_HAS_SCHEDULE = 'Entity must be idle to warp.'
export const WARP_HAS_CARGO = 'Entity must have no cargo to warp.'
export const WARP_NOT_FULL_ENERGY = 'Entity must have full energy to warp.'
export const WARP_OUT_OF_RANGE = 'Destination exceeds warp range.'

export const ENTITY_NO_CRAFTER = 'Entity does not have crafting capability.'
export const RECIPE_NOT_FOUND = 'Recipe does not exist.'
export const RECIPE_INPUTS_INSUFFICIENT = 'Insufficient inputs for recipe.'
export const RECIPE_INPUTS_INVALID = 'Input cargo does not match recipe requirements.'
export const RECIPE_INPUTS_EXCESS = 'Provided inputs exceed recipe requirements.'
export const RECIPE_INPUTS_MIXED = 'All stacks for a recipe input must be the same resource.'
export const ITEM_NOT_DEPLOYABLE = 'Item cannot be deployed as an entity.'
export const DEPLOY_ENTITY_HAS_SCHEDULE = 'Entity must be idle to deploy.'
export const BLEND_INPUTS_MUST_MATCH = 'All blend inputs must be the same item.'
export const GATHER_NOT_ENOUGH_ENERGY = 'Gather requires more energy than entity has.'
export const GATHER_EXCEEDS_ENERGY_CAPACITY = "Gather drain exceeds entity's energy capacity."
export const CRAFT_NOT_ENOUGH_ENERGY = 'Craft requires more energy than entity has.'
export const CRAFT_EXCEEDS_ENERGY_CAPACITY = "Craft drain exceeds entity's energy capacity."
export const BLEND_REQUIRES_MULTIPLE = 'Blend requires at least two input stacks.'
export const BLEND_STAT_LESS_NOT_SUPPORTED = 'Stat-less items cannot be blended.'

export const MODULE_SLOT_INVALID = 'Module slot index is invalid.'
export const MODULE_SLOT_OCCUPIED = 'Module slot is already occupied.'
export const MODULE_SLOT_EMPTY = 'Module slot is empty.'
export const MODULE_TYPE_MISMATCH = 'Module type not allowed in this slot.'
export const MODULE_CARGO_NOT_FOUND = 'Module cargo not found.'
export const MODULE_NOT_MODULE = 'Item is not a module.'
export const MODULE_ENTITY_BUSY = 'Entity must be idle to modify modules.'
export const ITEM_NOT_PACKED_ENTITY = 'Item is not a packed entity.'

// SDK-only market errors (no contract counterpart yet)
export const ITEM_NOT_AVAILABLE_AT_LOCATION = 'Item is not tradeable at ship location.'
export const INSUFFICIENT_BALANCE = 'Insufficient balance.'
export const INSUFFICIENT_ITEM_QUANTITY = 'Insufficient quantity in cargo.'
export const INSUFFICIENT_ITEM_SUPPLY = 'Insufficient supply of item at location.'
